# ☁️ Cloud Build Configuration для автоматического деплоя

steps:
  # Step 1: Build Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/interactive-demo:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/interactive-demo:latest'
      - '-f'
      - 'scripts/Dockerfile.interactive'
      - '.'
    id: 'build-image'

  # Step 2: Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/interactive-demo:$COMMIT_SHA'
    id: 'push-image'

  # Step 3: Push latest tag
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/interactive-demo:latest'
    id: 'push-latest'

  # Step 4: Deploy to Cloud Run
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'interactive-demo'
      - '--image=gcr.io/$PROJECT_ID/interactive-demo:$COMMIT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=512Mi'
      - '--cpu=1'
      - '--max-instances=10'
      - '--min-instances=0'
      - '--port=8080'
      - '--set-env-vars=PROJECT_ID=$PROJECT_ID,REGION=us-central1'
    id: 'deploy-cloud-run'

# Images to save
images:
  - 'gcr.io/$PROJECT_ID/interactive-demo:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/interactive-demo:latest'

# Build options
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY
  
timeout: '1200s'
