# Main Cloud Build configuration for all microservices
# This builds and deploys all 5 services sequentially

steps:
  # ============================================
  # Frontend Service
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service:latest'
      - '-f'
      - 'services/frontend-service/Dockerfile'
      - 'services/frontend-service'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service']
    waitFor: ['build-frontend']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-frontend'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'frontend-service'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-frontend']

  # ============================================
  # Orchestrator Agent
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-orchestrator'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/orchestrator-agent:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/orchestrator-agent:latest'
      - '-f'
      - 'services/orchestrator-agent/Dockerfile'
      - 'services/orchestrator-agent'
    waitFor: ['deploy-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-orchestrator'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/orchestrator-agent']
    waitFor: ['build-orchestrator']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-orchestrator'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'orchestrator-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/orchestrator-agent:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
    waitFor: ['push-orchestrator']

  # ============================================
  # Report Reader Agent
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-report-reader'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/report-reader-agent:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/report-reader-agent:latest'
      - '-f'
      - 'services/report-reader-agent/Dockerfile'
      - 'services/report-reader-agent'
    waitFor: ['deploy-orchestrator']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-report-reader'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/report-reader-agent']
    waitFor: ['build-report-reader']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-report-reader'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'report-reader-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/report-reader-agent:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=2'
    waitFor: ['push-report-reader']

  # ============================================
  # Logic Understanding Agent
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-logic'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/logic-understanding-agent:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/logic-understanding-agent:latest'
      - '-f'
      - 'services/logic-understanding-agent/Dockerfile'
      - 'services/logic-understanding-agent'
    waitFor: ['deploy-report-reader']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-logic'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/logic-understanding-agent']
    waitFor: ['build-logic']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-logic'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'logic-understanding-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/logic-understanding-agent:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=2Gi'
      - '--cpu=2'
      - '--timeout=300'
    waitFor: ['push-logic']

  # ============================================
  # Visualization Agent
  # ============================================
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-visualization'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/visualization-agent:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/visualization-agent:latest'
      - '-f'
      - 'services/visualization-agent/Dockerfile'
      - 'services/visualization-agent'
    waitFor: ['deploy-logic']

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-visualization'
    args: ['push', '--all-tags', 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/visualization-agent']
    waitFor: ['build-visualization']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: 'deploy-visualization'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'visualization-agent'
      - '--image=us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/visualization-agent:$SHORT_SHA'
      - '--region=us-central1'
      - '--platform=managed'
      - '--allow-unauthenticated'
      - '--memory=1Gi'
      - '--cpu=1'
    waitFor: ['push-visualization']

# Timeout for entire build
timeout: '3600s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
