# Test Cloud Build Configuration
# Simple test to build and push frontend-service to Artifact Registry

steps:
  # Build Docker image for frontend-service
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build-frontend'
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service:$SHORT_SHA'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service:latest'
      - '-f'
      - 'services/frontend-service/Dockerfile'
      - 'services/frontend-service'

  # Push Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: 'push-frontend'
    args:
      - 'push'
      - '--all-tags'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/financial-reports/frontend-service'
    waitFor: ['build-frontend']

# Simple timeout
timeout: '900s'

# Options
options:
  logging: CLOUD_LOGGING_ONLY
  machineType: 'E2_HIGHCPU_8'
